spring.datasource.url=jdbc:timesten:client:TTC_SERVER=164.92.189.67;TCP_PORT=6625;TTC_SERVER_DSN=SmartCarDB;UID=TIMESTEN
spring.datasource.driver-class-name=com.timesten.jdbc.TimesTenDriver
spring.datasource.username=TIMESTEN
spring.datasource.password=timesten123

spring.datasource.hikari.pool-name=TimesTenPool
spring.datasourceq.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.mvc.favicon.enabled=false

server.port=8080